## Nykaa Product Analysis: Healthcare, Beauty & Baby Products – Web Scraping + EDA

# Nykaa Web Scraping + EDA Project

### Objective:
Scrape product data from Nykaa using 3 category links:
1. Healthcare
2. Beauty
3. Baby

Then combine all the data into one dataset for EDA.

### importing all libraries useful for webscrapping:

#### get request of makeup products

In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import re

In [2]:
all_products = []

for i in range(1, 201):   # 1 to 201 pages

    url = f"https://www.nykaa.com/search/result/?q=makeup%20products&root=search&searchType=history&suggestionType=query&ssp={i}"

    r = requests.get(url)
    print("Page:", i, "Status Code:", r.status_code)

    if r.status_code != 200:
        continue

    soup = BeautifulSoup(r.text, "html.parser")

    names = soup.find_all("div", class_="css-xrzmfa")
    selling = soup.find_all("span", class_="css-111z9ua")
    mrps = soup.find_all("span", class_="css-17x46n5")
    disc = soup.find_all("span", class_="css-cjd9an")
    tags = soup.find_all("li", class_="custom-tag")
    rate=soup.find_all("span",class_="css-1qbvrhp")  # example


    for j in range(len(names)):

        product_name = names[j].text.strip()
    
        selling_price = selling[j].text.strip() if j < len(selling) else ""
        mrp = mrps[j].text.strip() if j < len(mrps) else ""
        discount = disc[j].text.strip().replace("Off", "").strip() if j < len(disc) else ""
        tag = tags[j].text.strip() if j < len(tags) else "None"
    
        rating = rate[j].text.strip() if j < len(rate) else ""
    
        all_products.append({
            "Product Name": product_name,
            "MRP": mrp,
            "Selling Price": selling_price,
            "Discount": discount,
            "Tag": tag,
            "Rating": rating
        })

# DataFrame
df1 = pd.DataFrame(all_products)


df1

Page: 1 Status Code: 200
Page: 2 Status Code: 200
Page: 3 Status Code: 200
Page: 4 Status Code: 200
Page: 5 Status Code: 200
Page: 6 Status Code: 200
Page: 7 Status Code: 200
Page: 8 Status Code: 200
Page: 9 Status Code: 200
Page: 10 Status Code: 200
Page: 11 Status Code: 200
Page: 12 Status Code: 200
Page: 13 Status Code: 200
Page: 14 Status Code: 200
Page: 15 Status Code: 200
Page: 16 Status Code: 200
Page: 17 Status Code: 200
Page: 18 Status Code: 200
Page: 19 Status Code: 200
Page: 20 Status Code: 200
Page: 21 Status Code: 200
Page: 22 Status Code: 200
Page: 23 Status Code: 200
Page: 24 Status Code: 200
Page: 25 Status Code: 200
Page: 26 Status Code: 200
Page: 27 Status Code: 200
Page: 28 Status Code: 200
Page: 29 Status Code: 200
Page: 30 Status Code: 200
Page: 31 Status Code: 200
Page: 32 Status Code: 200
Page: 33 Status Code: 200
Page: 34 Status Code: 200
Page: 35 Status Code: 200
Page: 36 Status Code: 200
Page: 37 Status Code: 200
Page: 38 Status Code: 200
Page: 39 Status Code: 200
Page: 40 Status Code: 200
Page: 41 Status Code: 200
Page: 42 Status Code: 200
Page: 43 Status Code: 200
Page: 44 Status Code: 200
Page: 45 Status Code: 200
Page: 46 Status Code: 200
Page: 47 Status Code: 200
Page: 48 Status Code: 200
Page: 49 Status Code: 200
Page: 50 Status Code: 200
Page: 51 Status Code: 200
Page: 52 Status Code: 200
Page: 53 Status Code: 200
Page: 54 Status Code: 200
Page: 55 Status Code: 200
Page: 56 Status Code: 200
Page: 57 Status Code: 200
Page: 58 Status Code: 200
Page: 59 Status Code: 200
Page: 60 Status Code: 200
Page: 61 Status Code: 200
Page: 62 Status Code: 200
Page: 63 Status Code: 200
Page: 64 Status Code: 200
Page: 65 Status Code: 200
Page: 66 Status Code: 200
Page: 67 Status Code: 200
Page: 68 Status Code: 200
Page: 69 Status Code: 200
Page: 70 Status Code: 200
Page: 71 Status Code: 200
Page: 72 Status Code: 200
Page: 73 Status Code: 200
Page: 74 Status Code: 200
Page: 75 Status Code: 200
Page: 76 Status Code: 200
Page: 77 Status Code: 200
Page: 78 Status Code: 200
Page: 79 Status Code: 200
Page: 80 Status Code: 200
Page: 81 Status Code: 200
Page: 82 Status Code: 200
Page: 83 Status Code: 200
Page: 84 Status Code: 200
Page: 85 Status Code: 200
Page: 86 Status Code: 200
Page: 87 Status Code: 200
Page: 88 Status Code: 200
Page: 89 Status Code: 200
Page: 90 Status Code: 200
Page: 91 Status Code: 200
Page: 92 Status Code: 200
Page: 93 Status Code: 200
Page: 94 Status Code: 200
Page: 95 Status Code: 200
Page: 96 Status Code: 200
Page: 97 Status Code: 200
Page: 98 Status Code: 200
Page: 99 Status Code: 200
Page: 100 Status Code: 200
Page: 101 Status Code: 200
Page: 102 Status Code: 200
Page: 103 Status Code: 200
Page: 104 Status Code: 200
Page: 105 Status Code: 200
Page: 106 Status Code: 200
Page: 107 Status Code: 200
Page: 108 Status Code: 200
Page: 109 Status Code: 200
Page: 110 Status Code: 200
Page: 111 Status Code: 200
Page: 112 Status Code: 200
Page: 113 Status Code: 200
Page: 114 Status Code: 200
Page: 115 Status Code: 200
Page: 116 Status Code: 200
Page: 117 Status Code: 200
Page: 118 Status Code: 200
Page: 119 Status Code: 200
Page: 120 Status Code: 200
Page: 121 Status Code: 200
Page: 122 Status Code: 200
Page: 123 Status Code: 200
Page: 124 Status Code: 200
Page: 125 Status Code: 200
Page: 126 Status Code: 200
Page: 127 Status Code: 200
Page: 128 Status Code: 200
Page: 129 Status Code: 200
Page: 130 Status Code: 200
Page: 131 Status Code: 200
Page: 132 Status Code: 200
Page: 133 Status Code: 200
Page: 134 Status Code: 200
Page: 135 Status Code: 200
Page: 136 Status Code: 200
Page: 137 Status Code: 200
Page: 138 Status Code: 200
Page: 139 Status Code: 200
Page: 140 Status Code: 200
Page: 141 Status Code: 200
Page: 142 Status Code: 200
Page: 143 Status Code: 200
Page: 144 Status Code: 200
Page: 145 Status Code: 200
Page: 146 Status Code: 200
Page: 147 Status Code: 200
Page: 148 Status Code: 200
Page: 149 Status Code: 200
Page: 150 Status Code: 200
Page: 151 Status Code: 200
Page: 152 Status Code: 200
Page: 153 Status Code: 200
Page: 154 Status Code: 200
Page: 155 Status Code: 200
Page: 156 Status Code: 200
Page: 157 Status Code: 200
Page: 158 Status Code: 200
Page: 159 Status Code: 200
Page: 160 Status Code: 200
Page: 161 Status Code: 200
Page: 162 Status Code: 200
Page: 163 Status Code: 200
Page: 164 Status Code: 200
Page: 165 Status Code: 200
Page: 166 Status Code: 200
Page: 167 Status Code: 200
Page: 168 Status Code: 200
Page: 169 Status Code: 200
Page: 170 Status Code: 200
Page: 171 Status Code: 200
Page: 172 Status Code: 200
Page: 173 Status Code: 200
Page: 174 Status Code: 200
Page: 175 Status Code: 200
Page: 176 Status Code: 200
Page: 177 Status Code: 200
Page: 178 Status Code: 200
Page: 179 Status Code: 200
Page: 180 Status Code: 200
Page: 181 Status Code: 200
Page: 182 Status Code: 200
Page: 183 Status Code: 200
Page: 184 Status Code: 200
Page: 185 Status Code: 200
Page: 186 Status Code: 200
Page: 187 Status Code: 200
Page: 188 Status Code: 200
Page: 189 Status Code: 200
Page: 190 Status Code: 200
Page: 191 Status Code: 200
Page: 192 Status Code: 200
Page: 193 Status Code: 200
Page: 194 Status Code: 200
Page: 195 Status Code: 200
Page: 196 Status Code: 200
Page: 197 Status Code: 200
Page: 198 Status Code: 200
Page: 199 Status Code: 200
Page: 200 Status Code: 200

,Product Name,MRP,Selling Price,Discount,Tag,Rating
0,"Lakme 9 To 5 Powerplay Matte Compact, Oil Cont...",₹650,₹520,20%,AD,( 165446 )
1,Nykaa Matte To Last ! Transferproof Liquid Lip...,₹749,₹487,35%,BESTSELLER,( 2388915 )
2,Nykaa Cosmetics So Creme! Creamy Matte Lipstick,₹329,₹214,35%,BESTSELLER,( 4027582 )
3,"Swiss Beauty Bold Matt Lip Liner Pencil, Long-...",₹1099,₹69,10%,BESTSELLER,( 263353 )
4,d'you Good Grease Twist Easy Cleansing Balm,₹749,₹2000,40%,BESTSELLER,( 45 )
...,...,...,...,...,...,...
3995,Daily Life Forever52 Pro Artist Ultra Definiti...,,₹1619,,BESTSELLER,( 15626 )
3996,Charlotte Tilbury Airbrush Flawless Foundation...,,₹5100,,BESTSELLER,( 77459 )
3997,Charlotte Tilbury Matte Revolution,,₹3650,,BESTSELLER,( 66848 )
3998,"LOreal Paris Infallible Full Wear Concealer, M...",,₹552,,AD,( 68064 )
3999,Maybelline Lash Sensational Sky High Mascara C...,,₹479,,BESTSELLER,( 72499 )

In [13]:
def get_brand(product_name):
    words = product_name.split()

    if len(words) == 0:
        return ""

    if len(words) == 1:
        return words[0]

    # mostly brand is 1 or 2 words
    first = words[0]
    second = words[1]

    # if second word is not brand type then keep only 1 word
    not_brand_words = ["New", "Pro", "Professional", "Matte", "Ultra", "Perfect", "Long", "Liquid", "Super"]

    if second in not_brand_words:
        return first
    else:
        return first + " " + second


df1["Brand Name"] = df1["Product Name"].apply(get_brand)

df1

,Product Name,MRP,Selling Price,Discount,Tag,Rating,Brand Name
0,Lakme 9 To 5 Powerplay Matte Compact Oil Contr...,₹650,₹520,20%,AD,( 165446 ),Lakme 9
1,Nykaa Matte To Last Transferproof Liquid Lips...,₹749,₹487,35%,BESTSELLER,( 2388915 ),Nykaa
2,Nykaa Cosmetics So Creme Creamy Matte Lipstick,₹329,₹214,35%,BESTSELLER,( 4027582 ),Nykaa Cosmetics
3,Swiss Beauty Bold Matt Lip Liner Pencil Longla...,₹1099,₹69,10%,BESTSELLER,( 263353 ),Swiss Beauty
4,dyou Good Grease Twist Easy Cleansing Balm,₹749,₹2000,40%,BESTSELLER,( 45 ),dyou Good
...,...,...,...,...,...,...,...
3995,Daily Life Forever52 Pro Artist Ultra Definiti...,,₹1619,,BESTSELLER,( 15626 ),Daily Life
3996,Charlotte Tilbury Airbrush Flawless Foundation...,,₹5100,,BESTSELLER,( 77459 ),Charlotte Tilbury
3997,Charlotte Tilbury Matte Revolution,,₹3650,,BESTSELLER,( 66848 ),Charlotte Tilbury
3998,LOreal Paris Infallible Full Wear Concealer Ma...,,₹552,,AD,( 68064 ),LOreal Paris
3999,Maybelline Lash Sensational Sky High Mascara C...,,₹479,,BESTSELLER,( 72499 ),Maybelline Lash

In [14]:
df1.tail()

,Product Name,MRP,Selling Price,Discount,Tag,Rating,Brand Name
3995,Daily Life Forever52 Pro Artist Ultra Definiti...,,₹1619,,BESTSELLER,( 15626 ),Daily Life
3996,Charlotte Tilbury Airbrush Flawless Foundation...,,₹5100,,BESTSELLER,( 77459 ),Charlotte Tilbury
3997,Charlotte Tilbury Matte Revolution,,₹3650,,BESTSELLER,( 66848 ),Charlotte Tilbury
3998,LOreal Paris Infallible Full Wear Concealer Ma...,,₹552,,AD,( 68064 ),LOreal Paris
3999,Maybelline Lash Sensational Sky High Mascara C...,,₹479,,BESTSELLER,( 72499 ),Maybelline Lash

In [15]:
df1.insert(0, "Category", "Makeup")

In [30]:
#df1.tail()

In [16]:
df1["Product Name"] = df1["Product Name"].apply(lambda x: re.sub(r"[^A-Za-z0-9 ]", "", x))

In [4]:
df1.to_csv("nykaa_makeup.csv",index=False)
print("CSV Saved Successfully")

CSV Saved Successfully

In [10]:
import os
print(os.path.exists("nykaa_makeup.csv"))

True

In [17]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4000 entries, 0 to 3999
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Category       4000 non-null   object
 1   Product Name   4000 non-null   object
 2   MRP            4000 non-null   object
 3   Selling Price  4000 non-null   object
 4   Discount       4000 non-null   object
 5   Tag            4000 non-null   object
 6   Rating         4000 non-null   object
 7   Brand Name     4000 non-null   object
dtypes: object(8)
memory usage: 250.1+ KB

## babycare products:

In [78]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

all_products = []

for i in range(2, 15):   #  pages 2 to 4 (increase if you want)

    url = f"https://www.nykaa.com/mom-baby/c/14797?page_no={i}&sort=popularity&transaction_id=3380af65d6d4182b6590650e22fa490a&intcmp=nykaa:sp:mom-and-baby:mom-and-baby:mom-and-baby-shop-all:COLUMN_GRID_V2:8:cta:-1:3380af65d6d4182b6590650e22fa490a"

    request1 = requests.get(url)
    print("Page:", i, "Status Code:", request1.status_code)

    if request1.status_code != 200:
        continue

    soup = BeautifulSoup(request1.text, "html.parser")

    names = soup.find_all("div", class_="css-xrzmfa")
    selling = soup.find_all("span", class_="css-111z9ua")
    mrps = soup.find_all("span", class_="css-17x46n5")
    disc = soup.find_all("span", class_="css-cjd9an")
    tags = soup.find_all("span", class_="css-1veplag")
    rate = soup.find_all("span", class_="css-1qbvrhp")

    for j in range(len(names)):

        product_name = names[j].text.strip()
        product_name = " ".join(product_name.split()[:6])

        selling_price = selling[j].text.strip() if j < len(selling) else ""
        mrp = mrps[j].text.strip() if j < len(mrps) else ""
        discount = disc[j].text.strip().replace("Off", "").strip() if j < len(disc) else ""
        tag = tags[j].text.strip() if j < len(tags) else "None"
        rating = rate[j].text.strip() if j < len(rate) else ""

        brand_name = (product_name.split()[:2]) if product_name != "" else ""

        all_products.append({
            "Category": "Baby Care",
            "Product Name": product_name,
            "MRP": mrp,
            "Selling Price": selling_price,
            "Discount": discount,
            "Tag": tag,
            "Rating": rating,
            "Brand Name": brand_name
        })

df2 = pd.DataFrame(all_products, columns=[
    "Category", "Product Name", "MRP", "Selling Price",
    "Discount", "Tag", "Rating", "Brand Name"
])

df2

Page: 2 Status Code: 200
Page: 3 Status Code: 200
Page: 4 Status Code: 200
Page: 5 Status Code: 200
Page: 6 Status Code: 200
Page: 7 Status Code: 200
Page: 8 Status Code: 200
Page: 9 Status Code: 200
Page: 10 Status Code: 200
Page: 11 Status Code: 200
Page: 12 Status Code: 200
Page: 13 Status Code: 200
Page: 14 Status Code: 200

,Category,Product Name,MRP,Selling Price,Discount,Tag,Rating,Brand Name
0,Baby Care,Forest Essentials Baby Body Massage Oil,₹1499,₹1895,8%,None,( 141 ),"[Forest, Essentials]"
1,Baby Care,Cetaphil Baby Wash & Shampoo with,₹600,₹1379,10%,None,( 1240 ),"[Cetaphil, Baby]"
2,Baby Care,Aveeno Baby Soothing Relief Face &,₹530,₹540,3%,None,( 869 ),"[Aveeno, Baby]"
3,Baby Care,"Sebamed Baby Shampoo, PH 5.5, Camomile,",₹2850,₹514,10%,None,( 943 ),"[Sebamed, Baby]"
4,Baby Care,ISDIN Fotoprotector Fusion Water Magic Pediatrics,₹676,₹2565,43%,None,( 1 ),"[ISDIN, Fotoprotector]"
...,...,...,...,...,...,...,...,...
255,Baby Care,Chicco Toothpaste - Mixed Fruit Flavour,₹530,₹179,25%,None,( 7 ),"[Chicco, Toothpaste]"
256,Baby Care,Beautiliss Silicone Body Scrubber Bath Brush,,₹110,,None,( 11 ),"[Beautiliss, Silicone]"
257,Baby Care,Parachute Advansed Baby Massage Oil,,₹492,,None,( 4 ),"[Parachute, Advansed]"
258,Baby Care,Bronson Professional Face Washing Microfiber A...,,₹300,,None,( 132 ),"[Bronson, Professional]"
259,Baby Care,Parachute Advansed Baby Gentle Wash,,₹398,,None,,"[Parachute, Advansed]"

In [79]:
df2.to_csv("Nykaa_baby_care_products.csv", index=False)
print("CSV saved successfully")

CSV saved successfully

In [80]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 260 entries, 0 to 259
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Category       260 non-null    object
 1   Product Name   260 non-null    object
 2   MRP            260 non-null    object
 3   Selling Price  260 non-null    object
 4   Discount       260 non-null    object
 5   Tag            260 non-null    object
 6   Rating         260 non-null    object
 7   Brand Name     260 non-null    object
dtypes: object(8)
memory usage: 16.4+ KB

## Health care products:

In [53]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

all_products = []

for i in range(2,19):   # ✅ page 2 to 4 (increase if you want)

    url = f"https://www.nykaa.com/wellness/c/671?page_no={i}&sort=popularity&transaction_id=8d74ee8167f377d921c9f85989bebbd9&intcmp=nykaa:sp:wellness-sale-page:wellness-sale:Shop_All:COLUMN_GRID_V2:9:wellness:-1:8d74ee8167f377d921c9f85989bebbd9"
    
    request2 = requests.get(url)
    print("Page:", i, "Status Code:", request2.status_code)

    if request2.status_code != 200:
        continue

    soup = BeautifulSoup(request2.text, "html.parser")

    names = soup.find_all("div", class_="css-xrzmfa")
    selling = soup.find_all("span", class_="css-111z9ua")
    mrps = soup.find_all("span", class_="css-17x46n5")
    disc = soup.find_all("span", class_="css-cjd9an")
    tags = soup.find_all("span", class_="css-1veplag")
    rate = soup.find_all("span", class_="css-1qbvrhp")

    for j in range(len(names)):

        product_name = names[j].text.strip()
        product_name = " ".join(product_name.split()[:6])

        selling_price = selling[j].text.strip() if j < len(selling) else ""
        mrp = mrps[j].text.strip() if j < len(mrps) else ""
        discount = disc[j].text.strip().replace("Off", "").strip() if j < len(disc) else ""
        tag = tags[j].text.strip() if j < len(tags) else "None"
        rating = rate[j].text.strip() if j < len(rate) else ""

        brand_name = " ".join(product_name.split()[:2]) if product_name != "" else ""

        all_products.append({
            "Category": "Wellness",
            "Product Name": product_name,
            "MRP": mrp,
            "Selling Price": selling_price,
            "Discount": discount,
            "Tag": tag,
            "Rating": rating,
            "Brand Name": brand_name
        })

df3 = pd.DataFrame(all_products, columns=[
    "Category", "Product Name", "MRP", "Selling Price",
    "Discount", "Tag", "Rating", "Brand Name"
])

df3

Page: 2 Status Code: 200
Page: 3 Status Code: 200
Page: 4 Status Code: 200
Page: 5 Status Code: 200
Page: 6 Status Code: 200
Page: 7 Status Code: 200
Page: 8 Status Code: 200
Page: 9 Status Code: 200
Page: 10 Status Code: 200
Page: 11 Status Code: 200
Page: 12 Status Code: 200
Page: 13 Status Code: 200
Page: 14 Status Code: 200
Page: 15 Status Code: 200
Page: 16 Status Code: 200
Page: 17 Status Code: 200
Page: 18 Status Code: 200

,Category,Product Name,MRP,Selling Price,Discount,Tag,Rating,Brand Name
0,Wellness,Orimii Belly Treatment Elixir - Body,₹695,₹626,10%,None,( 86 ),Orimii Belly
1,Wellness,Chicnutrix Glow - Japanese Glutathione &,₹695,₹1980,10%,None,( 2431 ),Chicnutrix Glow
2,Wellness,Orimii Bump Hydrating Body Butter for,₹2447,₹626,20%,None,( 95 ),Orimii Bump
3,Wellness,Glutone 1000 Setria L-Glutathione & Vitamin,₹1199,₹1958,25%,None,( 374 ),Glutone 1000
4,Wellness,Mountainor L Glutathione Tablets for Korean,₹1959,₹899,6%,None,( 4134 ),Mountainor L
...,...,...,...,...,...,...,...,...
335,Wellness,"Sirona Premium Disposable Maternity Breast Pads,",₹650,₹149,7%,None,( 115367 ),Sirona Premium
336,Wellness,"Palmer's Cocoa Butter Nursing Butter, For",₹299,₹450,21%,None,( 279 ),Palmer's Cocoa
337,Wellness,Max Care Virgin Coconut Oil -,₹800,₹605,25%,None,( 77 ),Max Care
338,Wellness,Sirona Pregrx Midstream One Step Urine,,₹236,,None,,Sirona Pregrx
339,Wellness,Plix ACV Apple Cider Vinegar L-carnitine,,₹599,,None,,Plix ACV

In [81]:
df3.to_csv("Nykaa_Health_care_products.csv", index=False)
print("CSV saved successfully")

CSV saved successfully

In [103]:
final_df = pd.concat([df1, df2, df3], axis=0, ignore_index=True)
final_df.to_csv("nykaa_final.csv", index=False)
print("CSV saved successfully")

CSV saved successfully

In [105]:
final_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4600 entries, 0 to 4599
Data columns (total 8 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Category       4600 non-null   object
 1   Product Name   4600 non-null   object
 2   MRP            4600 non-null   object
 3   Selling Price  4600 non-null   object
 4   Discount       4600 non-null   object
 5   Tag            4600 non-null   object
 6   Rating         4600 non-null   object
 7   Brand Name     4600 non-null   object
dtypes: object(8)
memory usage: 287.6+ KB